language: php
php:
  - 7.3
sudo: false
branches:
  only:
    - master
# Download Cecil
install:
  - curl -sSOL https://cecil.app/cecil.phar
# Display Cecil version
before_script:
  - php cecil.phar -v
# Run Cecil build
script:
  - php cecil.phar build -q
# Deploy to GitHub Pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: _site
  on:
    branch: master
