language: php
php:
  - 7
sudo: false
branches:
  only:
    - master
cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
# install dependencies
before_install:
  - phpenv config-rm xdebug.ini
install:
  - composer install --no-interaction
# build
script:
  - php scripts/build.php -e=prod
# deploy
deploy:
  provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: _site
    on:
      branch: master
# clear cache
after_deploy:
  - "curl -X DELETE \"https://api.cloudflare.com/client/v4/zones/${Cloudflare_zone}/purge_cache\" \
    -H \"X-Auth-Email: arnaud@ligny.org\" \
    -H \"X-Auth-Key: ${Cloudflare_API}\" \
    -H \"Content-Type: application/json\" \
    --data '{\"purge_everything\":true}'"
