language: php

php:
  - 7

sudo: false

branches:
  only:
    - master

#cache:
#  directories:
#    - vendor
#    - $COMPOSER_CACHE_DIR

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction

script:
  - php build.php -e=prod

after_success:
  - bash deploy.sh
  - "curl -X DELETE \"https://api.cloudflare.com/client/v4/zones/4a1f5f6d78237b32b1855255227d0bdf/purge_cache\" \
    -H \"X-Auth-Email: arnaud@ligny.org\" \
    -H \"X-Auth-Key: ${Cloudflare_API}\" \
    -H \"Content-Type: application/json\" \
    --data '{\"purge_everything\":true}'"
