title: "Narno.com"
baseurl: https://narno.com/
baseline: "dev web, vélo, bière et jeu vidéo !"
description: "Narno.com est un weblog où je parle de développement web, de vélo et de jeu vidéo."
keywords: [narno, blog, développement web, vélo, jeu vidéo]
language: fr
languages:
  - name: Français
    code: fr
    locale: fr_FR
menus:
  main:
    - name: 'Forum'
      id: forum
      url: https://lesforums.org
      weight: 1000
    - id: galeries
      enabled: false
date:
  format: "j M Y"
  timezone: "Europe/Paris"
author:
  name: "Arnaud Ligny"
  url: https://arnaudligny.fr
googleanalytics: UA-387892-1
virtualpages:
  - path: blog/le-blog-avance
    redirect: /
    title: "Le blog avance !"
    date: 2008-12-08
  - path: code
    redirect: https://github.com/Narno
social:
  facebook:
    admins: 516589570
    email: me@narno.com
    country: "France"
  twitter:
    username: "Narno"
  github:
    username: "Narno"
manifest:
  lang: fr-FR
  start_url: /
  display: standalone
  orientation: portrait
  background_color: "#ffffff"
  theme_color: "#202020"
serviceworker:
  enabled: false
  precache:
    - icon.png
    - css/poole.css
    - css/syntax.css
    - css/lanyon.css
    - css/narno.com.css
debug: false
comments: false
theme:
  - serviceworker
  - lanyon
editor: typora
optimize:
   enabled: true
cache:
  enabled: true
