title: "Narno.com"
baseurl: https://narno.com/
baseline: "dev web, vélo, bière et jeu vidéo !"
description: "Narno.com est un weblog où je parle de développement web, de vélo et de jeu vidéo."
keywords: [narno, blog, développement web, vélo, jeu vidéo]
language: fr
languages:
  fr:
    name: Français
    locale: fr_FR
date:
  format: "j M Y"
  timezone: "Europe/Paris"
author:
  name: "Arnaud Ligny"
  url: https://arnaudligny.fr
googleanalytics: UA-387892-1
virtualpages:
  code:
    redirect: https://github.com/Narno
  blog/le-blog-avance:
    redirect: /
    title: "Le blog avance !"
    date: 2008-12-08
rs:
  facebook:
    admins: 516589570
    email: me@narno.com
    country: "France"
  twitter:
    username: "Narno"
  github:
    username: "Narno"
menu:
  main:
  - identifier: about
    name: about hugo
    pre: <i class='fa fa-heart'></i>
    url: /about/
    weight: -110
  - name: getting started
    post: <span class='alert'>New!</span>
    pre: <i class='fa fa-road'></i>
    url: /getting-started/
    weight: -100
menu:
  main:
    - id: forum
      name: 'Forum'
      url: https://lesforums.org
      weight: 1000
menus:
  main:
    - id: home
      name: 'Home page'
    - id: other
      name: 'Other'
      url: https://other.com
      weight: 999
  footer:
    - id: about
      name: 'About'
menu-old:
  rs:
    twitter:
      id: twitter
      name: "Twitter"
      url: https://twitter.com/Narno
      weight: 1
    facebook:
      id: facebook
      name: "Facebook"
      url: https://www.facebook.com/narno
      weight: 2
    github:
      id: github
      name: "GitHub"
      url: https://github.com/Narno
      weight: 3
    drupal:
      id: drupal
      name: "Drupal"
      url: https://drupal.org/user/141690
      weight: 4
    senscritique:
      id: senscritique
      name: "SensCritique"
      url: https://www.senscritique.com/Narno
      weight: 5
    lastfm:
      id: lastfm
      name: "last.fm"
      url: https://www.last.fm/fr/user/narn0
      weight: 6
manifest:
  lang: fr-FR
  start_url: /
  display: standalone
  orientation: portrait
  background_color: "#ffffff"
  theme_color: "#202020"
serviceworker:
  enabled: false
  precache:
    - icon.png
    - css/poole.css
    - css/syntax.css
    - css/lanyon.css
    - css/narno.com.css
debug: false
comments: false
theme:
  - serviceworker
  - lanyon
editor: typora
optimize:
   enabled: true
