title: "Narno.com"
baseurl: https://narno.com/
baseline: "dev web, vélo, bière et jeu vidéo"
description: "Narno.com est un weblog où je partage mes expériences de développement web, de vélo et de jeu vidéo."
keywords: [développement web, vélo, jeu vidéo]
author:
  name: Narno
  email: me@narno.com
  url: https://narno.co
social:
  facebook:
    id: 516589570
    firstname: Arnaud
    lastname: Ligny
    username: Narno
    url: https://www.facebook.com/Narno
  twitter:
    site: Narno
    creator: Narno
    username: Narno
    url: https://twitter.com/Narno
  github:
    username: ArnaudLigny
    url: https://github.com/ArnaudLigny
  mastodon:
    username: Narno
    url: https://gazuji.com/@narno
  steam:
    username: narno
    url: https://steamcommunity.com/id/narno
language: fr
languages:
  - name: Français
    code: fr
    locale: fr_FR
date:
  format: "j M Y"
  timezone: "Europe/Paris"
theme:
  - pwa
  - lanyon
image: /icon-512x512.png
menus:
  main:
    - id: forum
      name: 'Forum'
      url: https://lesforums.org
      weight: 1000
    - id: galeries
      enabled: false
googleanalytics: UA-387892-1
virtualpages:
  - path: blog/le-blog-avance
    redirect: /
    title: "Le blog avance !"
    date: 2008-12-08
  - path: code
    redirect: https://github.com/Narno
manifest:
  background_color: "#ffffff"
  theme_color: "#202020"
  shortcuts: true
serviceworker:
  enabled: true
  precache:
    - icon-192x192.png
    - icon-512x512.png
disqus:
  enabled: false
  username: Narno
webmention: false
editor: typora
static:
  exclude: ['_backup']
metatags:
  jsonld:
    enabled: true
body:
  images:
    caption:
      enabled: true
    resize:
      enabled: true
    responsive:
      enabled: true
    webp:
      enabled: false
assets:
  images:
    optimize:
      enabled: true
    responsive:
      enabled: true
      sizes:
        default: '(min-width: 900px) 720px, (min-width: 620px) calc(7.69vw + 532px), (min-width: 480px) 416px, 92.5vw'
paths:
  - section: videos
    path: :section/:year/:month/:day/:slug
