title: "Narno.com"
baseurl: https://narno.com/
baseline: "dev web, vélo, bière et jeu vidéo"
description: "Narno.com est un weblog où je parle de développement web, de vélo et de jeu vidéo."
keywords: [narno, blog, développement web, vélo, jeu vidéo]
copyright: Arnaud Ligny
author:
  firstname: Arnaud
  name: Ligny
  email: me@narno.com
social:
  facebook:
    id: 516589570
    firstname: Arnaud
    lastname: Ligny
    username: Narno
  twitter:
    site: Narno
    creator: Narno
  github:
    username: Narno
me:
  - https://twitter.com/Narno
  - https://github.com/Narno
  - https://mamot.fr/@Narno
language: fr
languages:
  - name: Français
    code: fr
    locale: fr_FR
date:
  format: "j M Y"
  timezone: "Europe/Paris"
theme:
  - serviceworker
  - lanyon
image: /icon-512x512.png
menus:
  main:
    - name: 'Forum'
      id: forum
      url: https://lesforums.org
      weight: 1000
    - id: galeries
      enabled: false
googleanalytics: UA-387892-1
virtualpages:
  - path: blog/le-blog-avance
    redirect: /
    title: "Le blog avance !"
    date: 2008-12-08
  - path: code
    redirect: https://github.com/Narno
manifest:
  lang: fr-FR
  start_url: /
  display: standalone
  orientation: portrait
  background_color: "#ffffff"
  theme_color: "#202020"
serviceworker:
  enabled: false
  precache:
    - icon.png
    - css/poole.css
    - css/syntax.css
    - css/lanyon.css
    - css/narno.com.css
comments: false
editor: typora
static:
  exclude: ['*.css']
