title: Narno.com
baseurl: https://narno.com/
baseline: dev web, vélo, bière et jeu vidéo
description: Narno.com est un weblog où je partage mes expériences de développement web, de vélo et de jeu vidéo.
keywords: [développement web, vélo, jeu vidéo]
author:
  name: Narno
  email: me@narno.com
  url: https://narno.co
social:
  twitter:
    url: https://twitter.com/Narno
    site: Narno
    creator: Narno
  mastodon:
    url: https://gazuji.com/@narno
    creator: "@narno@gazuji.com"
  steam:
    url: https://steamcommunity.com/id/narno
    username: narno
language: fr
languages:
  - name: Français
    code: fr
    locale: fr_FR
date:
  format: "j M Y"
  timezone: "Europe/Paris"
theme:
  - pwa
  - lanyon
image: icon-512x512.png
menus:
  main:
    - id: forum
      name: Forum
      url: https://lesforums.org
      weight: 1000
      enabled: false
    - id: galeries
      enabled: false
googleanalytics: UA-387892-1
manifest:
  background_color: "#ffffff"
  theme_color: "#202020"
  shortcuts: true
serviceworker:
  enabled: true
  install:
    precache:
      - icon-192x192.png
      - icon-512x512.png
  update:
    snackbar:
      enabled: true
  offline:
    snackbar:
      enabled: true
disqus:
  enabled: false
  username: Narno
webmention: false
editor: typora
static:
  exclude: [_backup]
metatags:
  jsonld:
    enabled: true
pages:
  virtual:
    - path: blog/le-blog-avance
      redirect: /
      title: Le blog avance !
      date: 2008-12-08
  body:
    images:
      caption:
        enabled: true
      resize:
        enabled: true
      responsive:
        enabled: true
      formats: [webp]
assets:
  images:
    optimize:
      enabled: true
    responsive:
      enabled: true
      sizes:
        default: "(min-width: 900px) 720px, (min-width: 620px) calc(7.69vw + 532px), (min-width: 480px) 416px, 92.5vw"
paths:
  - section: videos
    path: :section/:year/:month/:day/:slug
