---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Blog
- type: directory
  path: content/blog
  label: Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: content/tags
  label: Tags
  create: documents
  match: "**/*"
  exclude: index.md
  new_doc_ext: md
- type: heading
  label: Pages
- type: document
  path: content/a-propos.md
  label: À propos
- type: document
  path: content/mes-velos.md
  label: Mes vélos
- type: document
  path: content/config-pc.md
  label: Config PC
- type: document
  path: content/soltek-eq3401-sp94-guide-montage.md
  label: Thermalright SP-94 dans un Soltek Qbic EQ3401
  match: "**/*"
- type: heading
  label: Data
- type: directory
  path: data
  label: Photos
  create: all
  match: data/photos/*.yml
  new_doc_ext: yml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - PHP_VERSION=7.2
  preview_output_directory: _site
  install_dependencies_command: bash .forestry/install.sh
  preview_docker_image: composer:latest
  mount_path: "/usr/src"
  working_dir: "/usr/src"
  instant_preview_command: php cecil.phar serve -v -d --host=0.0.0.0 --port=8080
