---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: config.yml
  label: Configuration
- type: heading
  label: Blog
- type: directory
  path: content/blog
  label: Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: content/tags
  label: Tags
  create: documents
  match: "**/*"
  exclude: index.md
  new_doc_ext: md
  templates:
  - tag
- type: heading
  label: Pages
- type: document
  path: content/config-pc.md
  label: Config PC
- type: document
  path: content/mes-velos.md
  label: Mes vélos
- type: document
  path: content/a-propos.md
  label: À propos
- type: heading
  label: Thermalright SP-94
- type: document
  path: content/soltek-eq3401-sp94-guide-montage.md
  label: Article
- type: document
  path: data/photos/soltek_eq3401/sp94_guide_montage.yml
  label: Photos
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - PHP_VERSION=7.2
  preview_output_directory: _site
  install_dependencies_command: bash .forestry/install.sh
  preview_docker_image: phpdocker/phpdocker:7.2
  mount_path: "/usr/src"
  working_dir: "/usr/src"
  instant_preview_command: php cecil.phar serve --host=0.0.0.0 --port=8080 -v -d --postprocess=no
