---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections: 
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - PHP_VERSION=7.2
  preview_output_directory: _site
  install_dependencies_command: bash .forestry/install.sh
  preview_docker_image: composer:latest
  mount_path: "/usr/src"
  working_dir: "/usr/src"
  instant_preview_command: php cecil.phar serve -v -d --host=0.0.0.0 --port=8080
